### ISSUE TITLE
Grid modifiers

### ISSUE THREAD

**Issue by ttomdewit** [lukewhitehouse/groot#2]
Option to make the grid gutter bigger (increase gutter with a simple class) or get rid of said gutter (adding a different class).

**Standard:**
`<div class="grid"></div>`

**Modifer:**
`<div class="grid grid--[modifier]></div>`

**Comment by lukewhitehouse** [comment]
Great shout @ttomdewit, I've added that into the [latest release](https://github.com/lukewhitehouse/groot/releases/tag/v0.0.4) in addition to a `.grid--compact` which zero's out the gutters.
